version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - 189
    - 66
    - 143
    - 213
    - 56
    - 203
    - 233
    - 66
    - 249
    - 176
    - 65
    - 63
    - 31
    - 244
    - 203
    - 95
  pan_id: 38536
  ext_pan_id:
    - 121
    - 118
    - 213
    - 107
    - 114
    - 198
    - 226
    - 248
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: Aith2UKa8chah4oodaSie5az9quieBeR8rieSooz8riepie7ooMoo5eeyee6Dahz
frontend:
  enabled: true
  port: 8099
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  adapter: zstack
devices:
  '0x0017880104238bf3':
    friendly_name: Living room hue lamp
  '0x0017880102183ab2':
    friendly_name: Hue dimmer switch 1
  '0xd44867fffe0179c9':
    friendly_name: TRV Living room
  '0xd44867fffe05f511':
    friendly_name: TRV Master Bedroom
  '0x54ef441000d6f1b9':
    friendly_name: Living room light switch
  '0x086bd7fffe5b8135':
    friendly_name: Kitchen surface lights
  '0x00158d0007efe860':
    friendly_name: Motion sensor kitchen
  '0x00178801082b1230':
    friendly_name: Bedroom lamp
  '0x0cae5ffffed0e07e':
    friendly_name: TRV Bedroom
  '0x54ef441000cf4915':
    friendly_name: Kitchen main lights
  '0x00158d0009777b8d':
    friendly_name: Sensor living room
  '0x00158d0009775e46':
    friendly_name: Sensor master bedroom
  '0x54ef441000d7004f':
    friendly_name: Bedroom main lights
  '0x00158d0007e7513c':
    friendly_name: Hallway motion
  '0xa4c138cd1dd895d1':
    friendly_name: Living room lamp 1
  '0xa4c138e23c9ad56f':
    friendly_name: Master bedroom lamp
  '0x0017880106e8d51d':
    friendly_name: Master bedroom wireless switch
  '0xcc86ecfffe1b2efb':
    friendly_name: Master bedroom blinds
  '0x00178801082af4a5':
    friendly_name: Hall light 1
  '0x001788010d716464':
    friendly_name: Hall light 2
  '0x00158d008b85bf55':
    friendly_name: Front door sensor
  '0x001788010d7411be':
    friendly_name: Living room lamp tall
  '0x00124b002510a7c7':
    friendly_name: Cosy button
  '0x00158d008c4a18b7':
    friendly_name: Bedroom sensor
groups: {}
availability:
  enabled: true
